name: Deploy Infra and frontend DEV

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    uses: ./.github/workflows/infra-deploy.yml
    with:
      aws_role: ${{ vars.DEV_INFRA_AWS_ROLE }}
      aws_region: ${{ vars.DEV_AWS_REGION }}
      aws_account_id: ${{ vars.DEV_AWS_ACCOUNT_ID }}

      env_name: dev
      code_dir: ${{ vars.INFRA_CODE_DIR }}
      tf_version: ${{ vars.TF_VERSION }}

      project_name: ${{ vars.PROJECT_NAME }}
      email_domain: ${{ vars.DEV_EMAIL_DOMAIN }}
      api_domain: ${{ vars.DEV_API_DOMAIN }}
      hosted_zone_id: ${{ vars.DEV_AWS_HOSTED_ZONE_ID }}

  output-infra:
    needs: deploy-infra
    uses: ./.github/workflows/infra-output.yml

    with:
      aws_role: ${{ vars.DEV_INFRA_AWS_ROLE }}
      aws_region: ${{ vars.DEV_AWS_REGION }}
      code_dir: ${{ vars.INFRA_CODE_DIR }}
      tf_version: ${{ vars.TF_VERSION }}
      env_name: dev

  deploy-frontend:
    needs: output-infra
    uses: ./.github/workflows/frontend.yml

    with:
      aws_role: ${{ vars.DEV_FRONTEND_AWS_ROLE }}
      aws_region: ${{ vars.DEV_AWS_REGION }}

      code_dir: ${{ vars.FRONTEND_CODE_DIR }}
      aws_bucket_name: ${{ needs.output-infra.outputs.s3_bucket_name }}
      aws_cloudfront_distribution_id: ${{ needs.output-infra.outputs.cloudfront_id }}

      api_domain: https://${{ vars.DEV_API_DOMAIN }}/
