name: Update dev Infra

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: eu-central-1
  credentials-account: arn:aws:iam::833095292836:role/Github-Terraform
  ENV_NAME: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.credentials-account }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      - name: Terraform Init
        working-directory: ./TF
        run: terraform init
      - name: Terraform Workspace
        working-directory: ./TF
        run: terraform workspace select -or-create ${{ env.ENV_NAME }}
      - name: Terraform Format
        working-directory: ./TF
        run: terraform fmt -check
      - name: Terraform Plan
        working-directory: ./TF
        run:
          terraform plan -var-file=${{ env.ENV_NAME }}.tfvars -input=false
          # On push to "main", deploy the Terraform infrastructure
      - name: Terraform Apply
        working-directory: ./TF
        if: github.ref == 'refs/heads/dev'
        run: terraform apply -var-file=${{ env.ENV_NAME }}.tfvars -auto-approve -input=false
