name: Deploy frontend Prod

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - vite-frontend/**
      - .github/workflows/frontend.yml
      - .github/workflows/prod-frontend.yml

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/frontend.yml
    with:
      aws_role: ${{ vars.PROD_FRONTEND_AWS_ROLE }}
      aws_region: ${{ vars.PROD_AWS_REGION }}

      code_dir: ${{ vars.FRONTEND_CODE_DIR }}
      aws_bucket_name: ${{ vars.PROD_FRONTEND_AWS_BUCKET_NAME }}
